### PR TITLE
Making changes

### PR DESCRIPTION
**Pull request by BradenLWeber**
Fixes these issues from the Trello board: 
- Clear text input on screen change
- add long press "drop pin" option
- Limit map zoom
- Redesign public/private bar
- Make public/private boards a different color
- Fix bugs using userBar while on Boards screen
- Get rid of board modal and put delete board directly onto board
- Change settings label

### CODE REVIEW

**Comment by EleanorLee42** [comment]
Testing new functionalities:
- ❌  Clear text input on screen change
  - `Boards` search bar does this fine
  - filter bar for pins throws an error: "undefined is not an object (evaluating 'pin.title.toLowerCase')"
  - in `map.jsx`, line 241
- ✅ add long press "drop pin" option 
  - ❗error msg when placing pin: "pin could not be placed with status: 500" ... but then it works? 
  - ❗when pins are clicked, only their titles show up... no notes or tags? 
- ✅ limit map zoom
- ✅ Redesign public/private bar
  - cute!! Love the little rectangle 😍 
- ✅ Make public/private boards a different color
- ✅ Fix bugs using userBar while on Boards screen
- ✅ Get rid of board modal and put delete board directly onto board
- ✅ change Settings label

**Comment by EleanorLee42** [comment]
Fixed clear text input error!! showPins() was used old attribute names for `pinname` and `pintag`.

**Comment by BradenLWeber** [comment]
Thank you so much for testing all these Eleanor! I think some things may have gotten a little mixed up with all the merging nonsense. I'll take a look at this probably tomorrow!

**Comment by BradenLWeber** [comment]
Okay, this is ready to be checked again!

**Comment by EleanorLee42** [comment]
Looks good to me!!

**Pull request merged**
