### PR TITLE
Geo location

### PR DESCRIPTION
**Pull request by BradenLWeber**

### CODE REVIEW

**Comment by rdicosola** [comment]
This looks like a great implementation of the geolocation part of the app! There are just a couple small issues:
1. sign up and login screens now crash the app on opening because "Non-serializable values were found in the navigation state"
2. there are many conflicting files, so we'll have to go through those at some point 
3. when you switch the boards from private to public, they move upwards and hide behind the switch component. 
great job braden!

**Comment by BradenLWeber** [comment]
Thanks for the comments Rebecca - they all should be fixed now! Turns out, I thought Eleanor's branch had dealt with the merge conflicts, but something went wrong so the actual "master" code looks like a mess right now. Once this PR is added, it should look tidied up

**Comment by rdicosola** [comment]
This looks great! Good job merging everything! There's only two very very small structural issues: 
1. the slider that switches been the public and private boards is backwards! says private when public boards are showing and public when the private boards are
2.  both the my boards and public boards buttons go to the public boards

These are not essential changes though so I'm going to merge this!

**Comment by BradenLWeber** [comment]
Ah yes - I ignored which button went to which board because I knew that was going to be replaced with the board icon later on. But the private and public being backwards - that's a good catch! We'll have to fix that later

**Pull request merged**
