### PR TITLE
Campus map

### PR DESCRIPTION
**Pull request by BradenLWeber**
- Now has the option of using a map of campus
- User can choose which map they want in the add board modal
- There are two default maps with nothing on them
- Board model has been changed so that a long title won't mess everything up

### CODE REVIEW

**Comment by BradenLWeber** [comment]
- Also includes ability to delete a pin

**Comment by EleanorLee42** [comment]
Hmm... delete pin removed ALL pins from the board for me. Did it remove the right one on your machine?

Campus map looks gorgeous, tho!!! Well done, Braden, as always. 🤩

**Comment by BradenLWeber** [comment]
Oh good catch! It's been fixed

**Comment by EleanorLee42** [comment]
Yay!! Looks swaggy 😁

**Pull request merged**
